version: 2
jobs:
  build:
    docker:
      - image: 'golang:1.10.3'
    steps:
      - checkout
      - run:
          name: Print the Current Time
          command: date
      - run: 
          name: Test
          environment:
            template: |
              {
                "user" : $CIRCLE_USERNAME,
                "branch": $CIRCLE_BRANCH,
                "number": $CIRCLE_SHA1
              }
          command: |
            hook_data=$(printf "$template")
            echo $explorer_stage_url
            # send integration test trigger to aws explorer stage server
            curl -X POST -H 'Content-Type: application/json' $explorer_stage_url -d $hook_data