version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run: 
          name: Test
          environment:
            template: |
              {
                "user" : $CIRCLE_USERNAME,
                "branch": $CIRCLE_BRANCH,
                "number": $CIRCLE_SHA1
              }
          command: |
            hook_data=$(printf "$template")
            # send integration test trigger to aws explorer stage server
            curl -X POST -H 'Content-Type: application/json' $explorer_stage_url --data "${hook_data:?}"